### ISSUE TITLE
It is time to update to Angular 1.3.13

### ISSUE THREAD

**Issue by eugef** [components/angular.js#17]
https://github.com/angular/angular.js/releases/tag/v1.3.13

**Comment by RobLoach** [comment]
@eugef If you put together a Pull Request for this, then we can get it in nicely. Thanks! :+1:

**Comment by martinlindhe** [comment]
I'm working on this now. In the future, please submit a pull request :-)

**Comment by martinlindhe** [comment]
https://github.com/components/angular.js/releases/tag/1.3.13

**Comment by eugef** [comment]
I would like to do it myself, but where can i find documentation how to update the component?

**Comment by martinlindhe** [comment]
eugef: docs, i dont know :-(

but it's quite simple, here's how i do it:

1. create a fork of our repository, check it out on your machine

2. download the latest 1.3.x zipfile from https://angularjs.org/

3. extract the zip file and copy the content (excluding the docs folder) into the repository you forked

4. "git status" and add new files etc, update component.json with the new version number

5. push your changes

6. on your github page of your forked repository, hit the "Pull request" link

**Comment by eugef** [comment]
@martinlindhe , thanks, it is easier that I expected
