### ISSUE TITLE
angularjs not loaded when installed via composer

### ISSUE THREAD

**Issue by harikt** [components/angular.js#6]
Hi I have installed angularjs and many other stuffs like foundation via composer.

But the angular is not defined. Is there anything I am missing? The foundation , jquery etc loads without any trouble.

I tried to edit the require.config.js of the require.config.js , but it is always over written when a composer update is made.

Thank you

**Comment by RobLoach** [comment]
@harikt Did you get it working?

**Comment by harikt** [comment]
That issue is not relevant any more.

**Comment by RobLoach** [comment]
@harikt What solution did you end up going with?

**Comment by marcosriso** [comment]
I had the same problem. In my local machine, it was working, but when cloning into server it was not downloading. My solution was to delete the folder vendor/components/angular.js/  and then running composer install / update again.
